/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  bestPractices: [
    {
      type: 'category',
      label: 'Best practices',
      link: {
        type: "doc",
        id: "best-practices"
      },
      items: [{ type: 'autogenerated', dirName: 'best-practices' }],
    },
  ],
  cheatSheets: [
    {
      type: 'category',
      label: 'Cheat sheets',
      link: {
        type: "doc",
        id: "cheatsheets"
      },
      items: [{ type: 'autogenerated', dirName: 'cheatsheets' }],
    },
  ],
};

module.exports = sidebars;
